<a href="https://colab.research.google.com/github/YangxuanWu/Python/blob/master/Python/Practice0614.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Create an DuPont Analysis/ROE application -- any language or platform of your choosing: 
 
#The app should accept the four needed inputs for DuPont Analysis.
#The app should calculate and display Profit Margin
#The app should calculate and display Total Asset Turnover
#The app should calculate and display Leverage Factor
#The app should calculate and display Return on Equity (ROE)

import math
NetIncome = int(input("NetIncome="))
Revenue = int(input("Revenue="))
AverageAssets = int(input("AverageAssets="))
RevenAverageEquityue = int(input("AverageEquity="))

TotalAssetTurnover = Revenue/AverageAssets
print ("TotalAssetTurnover=", TotalAssetTurnover)

PrifitMargin = NetIncome/Revenue
print ("PrifitMargin=", PrifitMargin)

LeverageFactor = AverageAssets/RevenAverageEquityue
print ("LeverageFactor=", LeverageFactor)

ROE = PrifitMargin*TotalAssetTurnover*LeverageFactor
print ("ROE=", PrifitMargin)

ROA = NetIncome/AverageAssets
print ("ROA=", ROA)



NetIncome=4
Revenue=3
AverageAssets=6
AverageEquity=7
TotalAssetTurnover= 0.5
PrifitMargin= 1.3333333333333333
LeverageFactor= 0.8571428571428571
ROE= 1.3333333333333333
ROA= 0.6666666666666666


In [0]:
def changeextend(str):
    #print string with extend
    mylist.extend([40,50,60]);
    print ("print string mylist:",mylist)
    return
def changeappend(str):
    #print string with append
    mylist.append( [7,8,9] )
    print ("print string mylist:",mylist)
    return
mylist = [10,20,30]
changeextend( mylist );
print ("print extend mylist:", mylist)
changeappend( mylist );
print ("print append mylist:", mylist)
#append() 方法用于在列表末尾添加新的对象
#extend() 函数用于在列表末尾一次性追加另一个序列中的多个值（用新列表扩展原来的列表）

print string mylist: [10, 20, 30, 40, 50, 60]
print extend mylist: [10, 20, 30, 40, 50, 60]
print string mylist: [10, 20, 30, 40, 50, 60, [7, 8, 9]]
print append mylist: [10, 20, 30, 40, 50, 60, [7, 8, 9]]


In [0]:
list1 = [1,2,3,4]
result = []
for x in list1:
    for y in list1:
        for z in list1:
            if x != y and x != z and y != z:
                a = x*100+y*10+z
                result.append(a)
 
print (result)
print (len(result))

[123, 124, 132, 134, 142, 143, 213, 214, 231, 234, 241, 243, 312, 314, 321, 324, 341, 342, 412, 413, 421, 423, 431, 432]
24


In [3]:
#转换为 list
info = 'abc'
a = list(info)
a[2] = 'd'
info = ' '.join(a)
print(info)

#使用字符串的 replace 函数
info = 'abc'
new_info = info.replace('c', 'd')
print(new_info)

#自我麻痹
a = 'Yangxuan'
b = 'python'
s = 'my name is %s, I love %s' % (a, b)
print (s)

a b d
abd
my name is Yangxuan, I love python


In [4]:
from keras.datasets import mnist
from numpy import array
import numpy as np
from numpy import uint8
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.


11493376/11490434 [==============================] - 2s 0us/step


In [5]:
train_images.shape
(60000, 28, 28)
len(train_labels)
60000
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
test_images.shape
len(test_labels)
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [0]:
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [0]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [0]:
#Flatten常规的几种用法：

In [18]:
#用在数组
from numpy import *
a = [[[1,2],3],[4,[5,6]],[7,8,9]]
a = array(a)
a.flatten()

array([list([[1, 2], 3]), list([4, [5, 6]]), list([7, 8, 9])],
      dtype=object)

In [19]:
a = [[1,3],[2,4],[3,5]]
a = array(a)
a.flatten()

array([1, 3, 2, 4, 3, 5])

In [20]:
#用在列表
a = [[1,3],[2,4],[3,5],["abc","def"]]
a1 = [y for x in a for y in x]#这里的逻辑关系理不清？？？
a1

[1, 3, 2, 4, 3, 5, 'abc', 'def']

In [21]:
#用在矩阵
a = [[1,3],[2,4],[3,5]]
a = mat(a)
y = a.flatten()
y

matrix([[1, 3, 2, 4, 3, 5]])

In [26]:
matrix([[1, 3, 2, 4, 3, 5]])
y = a.flatten().A#这里用到A是什么意思？？？
print (y)
print (shape(y))
print (shape(y[0]))

[[1 3 2 4 3 5]]
(1, 6)
(6,)


In [36]:
#（batch是这一组数据的数量；iteration：进行训练需要的总共的迭代次数；epoch：一次epoch是指将所有数据训练一遍的次数，epoch所代表的数字是指所有数据被训练的总轮数。）
#Loading the MNIST dataset in Keras 加载数据集
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
#The network architecture 设定网络体系结构
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))
#The compilation step 降维
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])
#Preparing the image data 图像数据
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255
#Preparing the labels 标签数据
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)
network.fit(train_images, train_labels, epochs=5, batch_size=128)
#测试学习结果
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)


Epoch 1/5
60000/60000 [==============================] - 4s 69us/step - loss: 0.2625 - accuracy: 0.9240
Epoch 2/5
60000/60000 [==============================] - 4s 69us/step - loss: 0.1026 - accuracy: 0.9697
Epoch 3/5
60000/60000 [==============================] - 4s 69us/step - loss: 0.0677 - accuracy: 0.9798
Epoch 4/5
60000/60000 [==============================] - 4s 68us/step - loss: 0.0491 - accuracy: 0.9847
Epoch 5/5
10000/10000 [==============================] - 0s 45us/step
test_acc: 0.9811000227928162
